{% set pyproject = load_file_data("pyproject.toml") %}
{% set project = pyproject["project"] %}
{% set version = project["version"] %}

package:
    name: {{ project["name"] }}
    # If this release is tagged, use bare version number. Otherwise,
    # append 'dev' to version number.
    # This scheme complies with PEP-386:
    # https://www.python.org/dev/peps/pep-0386/
    {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}
    version: {{ project["version"] }}
    {% else %}
    version: {{ project["version"] + "dev" }}
    {% endif %}


source:
    git_url: ../

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    noarch: python

requirements:
    host:
        - python >=3.10
        - astra-toolbox >=2.0
        - pip
        - setuptools >=61
        - wheel

    run:
        - python >=3.10
        - astra-toolbox >=2.0,!=2.3.0
        - numpy >=1.21

about:
    home: {{ project["urls"]["Homepage"] }}
    license: {{ project["license"]["text"] }}
    license_file: LICENSE
    summary: "{{ project["description"] }}"

extra:
    maintainers:
        - Dirk Schut
        - Allard Hendriksen
